import pickle
import numpy as np
import argparse
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm


def dict_to_string(data):
    """Recursively converts a dictionary or list to a descriptive string."""
    if isinstance(data, dict):
        return ", ".join([f"{k}: {dict_to_string(v)}" for k, v in data.items()])
    elif isinstance(data, list):
        return ", ".join([dict_to_string(item) for item in data])
    else:
        return str(data)


def compute_metrics(sim_matrix):
    """Computes Top-1, Top-5, and MRR from a similarity matrix."""
    num_queries = sim_matrix.shape[0]
    top1_hits = 0
    top5_hits = 0
    mrr_sum = 0.0

    for i in range(num_queries):
        # i is the index of the "correct" match for the i-th query
        scores = sim_matrix[i]
        rank_indices = np.argsort(scores)[::-1]

        # Find the rank of the correct item (1-based)
        rank = np.where(rank_indices == i)[0][0] + 1

        if rank == 1:
            top1_hits += 1
        if rank <= 5:
            top5_hits += 1

        mrr_sum += 1.0 / rank

    return {
        "top1": (top1_hits / num_queries) * 100,
        "top5": (top5_hits / num_queries) * 100,
        "mrr": mrr_sum / num_queries
    }


def evaluate_retrieval(pickle_path):
    print(f"Loading retrieval data from {pickle_path}...")
    with open(pickle_path, 'rb') as f:
        data = pickle.load(f)

    if not data:
        print("No data found in pickle file.")
        return

    print("Loading CLIP model for text encoding...")
    # Using the same CLIP model as the capture script to ensure embedding space alignment
    model = SentenceTransformer('clip-ViT-B-32')

    # Prepare data
    images = [item['image'] for item in data]
    # Handle cases where environment_landscape might be a dict or list
    captions = [dict_to_string(item.get('environment_landscape', "")) for item in data]
    
    # Ensure embeddings are numpy arrays
    image_embeddings = np.array([item['image_embedding'] for item in data])

    print(f"Dataset size: {len(images)} images")
    print("Encoding captions...")
    text_embeddings = model.encode(captions, show_progress_bar=True)

    # Calculate similarity matrix
    # sim_matrix[i, j] is similarity between caption i and image j
    print("Calculating similarity matrix...")
    sim_matrix = cosine_similarity(text_embeddings, image_embeddings)

    print("Evaluating Text-to-Image (T2I) retrieval...")
    t2i_metrics = compute_metrics(sim_matrix)

    print("Evaluating Image-to-Text (I2T) retrieval...")
    # For I2T, we query with images and look for the correct caption
    # This is equivalent to taking the transpose of the similarity matrix
    i2t_metrics = compute_metrics(sim_matrix.T)

    print("\n" + "=" * 45)
    print(f"{'METRIC':<20} | {'T2I':<10} | {'I2T':<10}")
    print("-" * 45)
    print(f"{'Total Queries':<20} | {len(images):<10} | {len(images):<10}")
    print(f"{'Top-1 Accuracy':<20} | {t2i_metrics['top1']:>9.2f}% | {i2t_metrics['top1']:>9.2f}%")
    print(f"{'Top-5 Accuracy':<20} | {t2i_metrics['top5']:>9.2f}% | {i2t_metrics['top5']:>9.2f}%")
    print(f"{'MRR':<20} | {t2i_metrics['mrr']:>10.4f} | {i2t_metrics['mrr']:>10.4f}")
    print("=" * 45)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate Image Retrieval performance from VLM captions.")
    parser.add_argument("--pickle_file", type=str, help="Path to the .pkl file generated by caption_test.py")
    args = parser.parse_args()

    evaluate_retrieval(args.pickle_file)
