import pickle
import numpy as np
import argparse
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

def evaluate_retrieval(pickle_path):
    print(f"Loading retrieval data from {pickle_path}...")
    with open(pickle_path, 'rb') as f:
        data = pickle.load(f)
    
    if not data:
        print("No data found in pickle file.")
        return

    print("Loading CLIP model for text encoding...")
    # Using the same CLIP model as the capture script to ensure embedding space alignment
    model = SentenceTransformer('clip-ViT-B-32')

    # Prepare data
    images = [item['image'] for item in data]
    captions = [item['environment_landscape'] for item in data]
    # Ensure embeddings are numpy arrays
    image_embeddings = np.array([item['image_embedding'] for item in data])

    print(f"Dataset size: {len(images)} images")
    print("Encoding captions...")
    text_embeddings = model.encode(captions, show_progress_bar=True)

    # Calculate similarity matrix (Text-to-Image)
    # Each row is a query (caption), each column is a candidate (image)
    print("Calculating similarity matrix...")
    sim_matrix = cosine_similarity(text_embeddings, image_embeddings)

    # Metrics
    top1_hits = 0
    top5_hits = 0
    mrr_sum = 0.0
    num_queries = len(images)

    print("Evaluating ranks...")
    for i in range(num_queries):
        # Sort indices by similarity in descending order
        # i is the index of the "correct" image for the i-th caption
        scores = sim_matrix[i]
        rank_indices = np.argsort(scores)[::-1]
        
        # Find the rank of the correct image (1-based)
        rank = np.where(rank_indices == i)[0][0] + 1
        
        if rank == 1:
            top1_hits += 1
        if rank <= 5:
            top5_hits += 1
        
        mrr_sum += 1.0 / rank

    # Final Statistics
    top1_acc = (top1_hits / num_queries) * 100
    top5_acc = (top5_hits / num_queries) * 100
    mrr = mrr_sum / num_queries

    print("\n" + "="*30)
    print("RETRIEVAL EVALUATION RESULTS")
    print("="*30)
    print(f"Total Queries:    {num_queries}")
    print(f"Top-1 Accuracy:   {top1_acc:.2f}%")
    print(f"Top-5 Accuracy:   {top5_acc:.2f}%")
    print(f"MRR:              {mrr:.4f}")
    print("="*30)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate Image Retrieval performance from VLM captions.")
    parser.add_argument("pickle_file", type=str, help="Path to the .pkl file generated by caption_test.py")
    args = parser.parse_args()
    
    evaluate_retrieval(args.pickle_file)
