import pickle
import numpy as np
import torch
import argparse
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm
from transformers import AutoModel


def dict_to_string(data):
    """Recursively converts a dictionary or list to a descriptive string."""
    if isinstance(data, dict):
        return ", ".join([f"{k}: {dict_to_string(v)}" for k, v in data.items()])
    elif isinstance(data, list):
        return ", ".join([dict_to_string(item) for item in data])
    else:
        return str(data)


def compute_metrics(sim_matrix):
    """Computes Top-1, Top-5, and MRR from a similarity matrix."""
    num_queries = sim_matrix.shape[0]
    top1_hits = 0
    top5_hits = 0
    mrr_sum = 0.0

    for i in range(num_queries):
        # i is the index of the "correct" match for the i-th query
        scores = sim_matrix[i]
        rank_indices = np.argsort(scores)[::-1]

        # Find the rank of the correct item (1-based)
        rank = np.where(rank_indices == i)[0][0] + 1

        if rank == 1:
            top1_hits += 1
        if rank <= 5:
            top5_hits += 1

        mrr_sum += 1.0 / rank

    return {
        "top1": (top1_hits / num_queries) * 100,
        "top5": (top5_hits / num_queries) * 100,
        "mrr": mrr_sum / num_queries
    }


def evaluate_retrieval(pickle_path, use_tips_embeddings=False):
    print(f"Loading retrieval data from {pickle_path}...")
    with open(pickle_path, 'rb') as f:
        data = pickle.load(f)

    if not data:
        print("No data found in pickle file.")
        return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Load Tips model")
    tips_model = AutoModel.from_pretrained("google/tipsv2-b14", trust_remote_code=True)
    tips_model.eval().to(device)

    print("Loading CLIP model for text encoding...")
    # Using the same CLIP model as the capture script to ensure embedding space alignment
    model = SentenceTransformer('clip-ViT-B-32')

    # Prepare data
    images = [item['image'] for item in data]
    
    # Define the components to evaluate
    component_keys = [
        'combined_caption',
        'visible_evidence',
        'human_activities',
        'land_cover_usage',
        'type_of_vegetation'
    ]

    # Ensure image embeddings are numpy arrays
    if use_tips_embeddings:
        image_embeddings = np.array([item['tips_image_embedding'] for item in data])
    else:
        image_embeddings = np.array([item["image_embedding"] for item in data])

    print(f"Dataset size: {len(images)} images")
    
    all_results = {}

    for key in component_keys:
        print(f"\n--- Evaluating Component: {key} ---")
        # Handle cases where value might be empty or missing
        raw_captions = [dict_to_string(item.get(key, "")) for item in data]
        
        # Format as "Category: Value" to provide context, especially for "none" values
        formatted_captions = []
        category_label = key.replace('_', ' ').capitalize()
        
        for c in raw_captions:
            val = c.strip() if c.strip() else "none"
            # Special case for combined_caption: don't prefix
            if key == 'combined_caption':
                formatted_captions.append(val)
            else:
                formatted_captions.append(f"{category_label}: {val}")
        
        print(f"Encoding '{key}'...")
        if use_tips_embeddings:
            text_embeddings = tips_model.encode_text(formatted_captions).detach().cpu().numpy()
        else:
            text_embeddings = model.encode(formatted_captions, show_progress_bar=True)

        # Calculate similarity matrix
        print(f"Calculating similarity matrix for {key}...")
        sim_matrix = cosine_similarity(text_embeddings, image_embeddings)

        print(f"Evaluating T2I retrieval for {key}...")
        t2i_metrics = compute_metrics(sim_matrix)

        print(f"Evaluating I2T retrieval for {key}...")
        i2t_metrics = compute_metrics(sim_matrix.T)
        
        all_results[key] = {
            "t2i": t2i_metrics,
            "i2t": i2t_metrics
        }

    # Final Comparison Table
    print("\n" + "=" * 80)
    print(f"{'COMPONENT':<25} | {'T2I Top-1':<10} | {'T2I Top-5':<10} | {'I2T Top-1':<10} | {'I2T Top-5':<10}")
    print("-" * 80)
    for key in component_keys:
        res = all_results[key]
        print(f"{key:<25} | {res['t2i']['top1']:>9.2f}% | {res['t2i']['top5']:>9.2f}% | {res['i2t']['top1']:>9.2f}% | {res['i2t']['top5']:>9.2f}%")
    print("=" * 80)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate Image Retrieval performance from VLM captions.")
    parser.add_argument("--pickle_file", type=str, help="Path to the .pkl file generated by caption_test.py")
    parser.add_argument("--use_tips_embeddings", action="store_true",
                        help="Whether to use TIPS image embeddings for evaluation")
    args = parser.parse_args()

    evaluate_retrieval(args.pickle_file, use_tips_embeddings=args.use_tips_embeddings)
