import pickle
import h3
import numpy as np
import argparse
from sklearn.metrics.pairwise import cosine_similarity

def main():
    parser = argparse.ArgumentParser(description="Query the Geo-Embedding Space.")
    parser.add_argument("--pkl_file", type=str, required=True, help="Path to the .pkl file generated by process_scraped_data.py")
    parser.add_argument("--lat", type=float, required=True, help="Latitude of the query.")
    parser.add_argument("--lon", type=float, required=True, help="Longitude of the query.")
    parser.add_argument("--radius_cells", type=int, default=1, help="Search radius in H3 cells.")
    parser.add_argument("--top_k", type=int, default=5, help="Number of results to return.")
    args = parser.parse_args()

    print(f"Loading embedding space from {args.pkl_file}...")
    with open(args.pkl_file, 'rb') as f:
        data = pickle.load(f)
    
    # Identify the query cell
    # Assuming resolution 11 was used during creation
    # We should ideally store the resolution in the pkl, but for now we'll assume 11
    query_cell = h3.latlng_to_cell(args.lat, args.lon, 11)
    
    # Find neighboring cells
    nearby_cells = h3.grid_disk(query_cell, args.radius_cells)
    
    # Filter data by spatial proximity first (RAG optimization)
    candidates = [item for item in data if item['H3_Cell'] in nearby_cells]
    
    if not candidates:
        print("No images found in the specified spatial radius.")
        return

    print(f"Found {len(candidates)} candidates nearby. Sorting by... (Wait, no query image provided, just returning nearby)")
    
    # Since we don't have a query image here, we just return the closest spatially
    # In a real Geo-RAG, you'd provide a query image or text to find matches within these candidates.
    
    for i, item in enumerate(candidates[:args.top_k]):
        print(f"{i+1}. ID: {item['ID']} ({item['Platform']})")
        print(f"   Location: {item['Latitude']}, {item['Longitude']}")
        print(f"   URL: {item['Image_URL']}")
        print(f"   H3 Cell: {item['H3_Cell']}\n")

if __name__ == "__main__":
    main()
