# Caption Evaluation parameters
caption_evals:
  python_script: "src.evaluation.caption_test"
  img_dir: "/path/to/your/places365/val"
  labels_file: "/path/to/your/places365/Scene_hierarchy.xlsx"
  max_images: 1000
  models:
    - "gemma4:e4b"
  versions:
    - "v1"
