# LUCAS Evaluation parameters
lucas_evals:
  python_script: "src.evaluation.evaluate_lucas"
  img_dir: "/path/to/your/LUCAS2018"
  csv_file: "/path/to/your/LUCAS2018/Sen4Map_Metadata_test.csv"
  max_images: 1000
  models:
    - "gemma4:e4b"
  versions:
    - "v3"
