# Offline Evaluation Configuration Parameters (LUCAS & Places365)

lucas:
  model_name: "vit_base_patch16_dinov3.lvd1689m"
  csv: "/home/ananthu/DATA/data_ananthu/LUCAS2018/Sen4Map_Metadata_test.csv"
  img_dir: "/home/ananthu/DATA/data_ananthu/LUCAS2018"
  num_queries: 3000
  num_database: 0
  batch_size: 32
  seed: 42
  use_segformer: false

places:
  model_name: "vit_base_patch16_dinov3.lvd1689m"
  labels: "/home/ananthu/DATA/data_ananthu/places365/versions/1/Scene_hierarchy.xlsx"
  img_dir: "/home/ananthu/DATA/data_ananthu/places365/versions/1/val"
  num_queries: 3000
  num_database: 0
  batch_size: 32
  seed: 42
  use_segformer: false
  compare_clip: false
