# OpenStreetMap Boundary Scraper Parameters
scraper:
  mode: "global"
  osm_query: "Montpellier, France"
  osm_relation: ""
  platforms: "kartaview"
  base_dir: "/home/ananthu/Projects/data/osm_scrape_rand_3"
  total_chunks: 10000
