# Exhaustive Natural LULC Vocabulary with Global Biomes
NATURAL_LULC_VOCAB = {
    "Broadleaved forest": "Deciduous or evergreen broad-leaf trees (oak, beech, maple, birch).",
    "Coniferous forest": "Evergreen needle-leaf trees (pine, spruce, fir, larch).",
    "Mixed forest": "Co-dominant broadleaved and coniferous trees.",
    "Tropical forest": "Equatorial rainforests, mangroves, or tropical dry forest.",
    "Sparsely wooded / Savanna": "Grassland with scattered trees (10-30% canopy cover).",
    "Natural grassland": "Meadows, wild steppes, alpine grasslands, or prairies.",
    "Temperate shrubland / Scrub": "Low woody scrub (heather, gorse, bramble).",
    "Arid shrubland": "Desert scrub, sagebrush, or dry savanna bushland.",
    "Tundra": "Low-growing polar vegetation (mosses, lichens, dwarf shrubs).",
    "Sandy desert / Dunes": "Sand sheets, active dunes, or sandy flats.",
    "Rocky desert / Gravel plains": "Stony hamadas, gravel plains, or barren volcanic ash fields.",
    "Barren soil / Badlands": "Highly eroded clay hills, bare dry earth, or dry salt flats.",
    "Bare rock / Cliffs": "Exposed bedrock, cliffs, or scree slopes.",
    "Mountain peak / Alpine ridge": "High-altitude rocky ridges, jagged summits, or mountain peaks.",
    "Waterfall / Cascade": "Water flowing vertically over a cliff or steep drop.",
    "Volcanic terrain / Lava flow": "Barren basalt fields, volcanic craters, or active geothermal areas.",
    "Salt flat / Playa": "Dry lake beds covered with salt crusts or mineral deposits (e.g. Salar de Uyuni).",
    "Coastal beach / Spit": "Sandy or pebbly sea coast.",
    "Wetland / Marsh / Bog": "Marshes, peat bogs, fens, reed beds, or swamps.",
    "River / Stream": "Flowing freshwater channels, creeks, or canals.",
    "Lake / Pond": "Standing inland water bodies or reservoirs.",
    "Marine / Estuary": "Coastal saltwater, ocean surf, bays, or intertidal flats.",
    "Glacier / Permanent ice": "Glaciers, ice caps, or permanent snowfields.",
    "Other natural land cover": "Any other natural land cover or landscape.",
}

# Exhaustive Man-made LULC Vocabulary
MAN_MADE_LULC_VOCAB = {
    "Forest plantation": "Evenly spaced rows of planted timber trees.",
    "Managed pasture": "Fenced grazing pastures or paddocks.",
    "Herbaceous cropland": "Annual cultivated field crops (cereal, corn, wheat, canola).",
    "Orchards & Vineyards": "Woody perennial row crops (vineyards, fruit/olive orchards, plantations).",
    "Rice paddies / Flooded crops": "Water-flooded agricultural basins.",
    "Covered agriculture": "Greenhouses, polytunnels, or nurseries.",
    "High-density built-up": "Skyscrapers, high-rise blocks, and dense urban centers.",
    "Suburban / Low-density residential": "Single-family houses, villas, private gardens, and streets.",
    "Industrial / Commercial zone": "Factories, warehouses, refineries, shopping centers, or office parks.",
    "Active construction site": "Earthworks, building foundations, cranes, and scaffolding.",
    "Transportation network": "Highways, railways, runways, or shipping ports.",
    "Mine / Quarry / Landfill": "Open-pit mines, gravel quarries, or landfill sites.",
    "Urban green space": "City parks, golf courses, botanical gardens, or sports fields.",
    "Historical / Cultural monument / Archaeological site": "Ancient ruins, monuments, pyramids, historic temples, stone circles, or archaeological landmarks (e.g. Giza Pyramids, Taj Mahal, Stonehenge).",
    "Other man-made surface": "Any other artificial or managed land cover or surface.",
}
